sudo: false
language: python
python:
  - "2.7"


env:
  - MAILGUN_API_KEY=testtesttest

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script: coverage run --source=. -m unittest discover

after_success:
    - coveralls
